#!/bin/bash

alias l='ls -h'
alias la='l -A'
alias ll='l -l'
alias lR='l -R'
alias l1='l -1'
alias lss='ls *'
alias laa='la *'
alias lla='ll -A'
alias laR='la -R'

alias rmf='rm -rf'
alias gcf='gcc -Wall -Werror -Wextra'

alias py='python3'
alias py2='python2'

alias gg='~/g_Shell/git.sh'
alias open='~/g_Shell/open.sh'
alias wifi='~/g_Shell/wifi.sh'

alias sag='sudo apt-get'
alias sagp='sag purge'
alias sagu='sag update'
alias sagi='sag install'
alias sagug='sag upgrade'
alias sagac='sag autoclean'
alias sagfi='sag -f install'
alias sagar='sag autoremove'

alias gs='gg -s'
alias gp='gg -p'
alias gu='gg -u'
alias gc='git clone'

alias pdf='evince'
alias jpn='jupyter-notebook'
alias rmysql='mysql -u root -p'
alias chrome='chromium-browser'
