#!/bin/bash

alias la='ls -A'
alias ll='ls -l'
alias lr='ls -R'
alias l1='ls -1'
alias lss='ls *'
alias la1='ls -A1'
alias lla='ls -Al'
alias lar='ls -AR'
alias laa='ls -A *'
alias lls='ls -l *'
alias lar1='ls - AR1'
alias llar='ls -lAR'

alias su='sudo su'
alias py='python3'
alias py2='python2'
alias rmf='rm -rf'
alias pep='pep8'
alias pepa='pep8 *.py'
alias open='xdg-open'
alias tmex='tmux; exit'
alias jupyter='jupyter-notebook'

alias sag='sudo apt-get'
alias sagp='sag purge -y'
alias sagu='sag update -y'
alias sagi='sag install -y'
alias sagug='sag upgrade -y'
alias sagac='sag autoclean -y'
alias sagif='sag install -f -y'
alias sagar='sag autoremove -y'

alias grm='git rm'
alias gad='git add'
alias glg='git log'
alias gdf='git diff'
alias gpl='git pull'
alias gps='git push'
alias gcl='git clone'
alias gbr='git branch'
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit -m'

alias mysqlun='mysql -u narek -p'
alias mysqlun='sudo mysql -u root -p'
