#!/bin/bash

alias la='ls -A'
alias ll='ls -l'
alias lr='ls -R'

alias gad='git add'
alias glg='git log'
alias gdf='git diff'
alias gpl='git pull'
alias gps='git push'
alias gcl='git clone'
alias gbr='git branch'
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit -m'

alias rmf='rm -rf'
alias tmex='tmux; exit'

alias py='python3'
alias py2='python2'
alias python='python3'
alias pep='pycodestyle'
alias jupyter='jupyter-notebook'
