#!/bin/bash

alias la='ls -A'
alias ll='ls -l'
alias lr='ls -R'
alias l1='ls -1'
alias lss='ls *'
alias la1='ls -A1'
alias lla='ls -Al'
alias lar='ls -AR'
alias laa='ls -A *'
alias lls='ls -l *'

alias su='sudo su'
alias py='python3'
alias py2='python2'
alias rmf='rm -rf'
alias rmysql='mysql -u root -p'
alias chrome='chromium-browser'
alias jupyter='jupyter-notebook'

alias sag='sudo apt-get'
alias sagp='sag purge -y'
alias sagu='sag update -y'
alias sagi='sag install -y'
alias sagug='sag upgrade -y'
alias sagac='sag autoclean -y'
alias sagif='sag install -f -y'
alias sagar='sag autoremove -y'

alias grm='git rm'
alias gad='git add'
alias gpl='git pull'
alias gps='git push'
alias gcl='git clone'
alias grb='git branch'
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit -m'
