#!/bin/bash

alias l='ls -h'
alias la='l -A'
alias ll='l -l'
alias lR='l -R'
alias l1='l -1'
alias lss='ls *'
alias laa='la *'
alias la1='la -1'
alias lR1='lR -1'
alias lla='ll -A'
alias laR='la -R'

alias su='sudo su'
alias py='python3'
alias py2='python2'
alias rmf='rm -rf'
alias open='gnome-open'
alias jpn='jupyter-notebook'
alias rmysql='mysql -u root -p'
alias chrome='chromium-browser'
alias gcf='gcc -Wall -Werror -Wextra'

alias gg='/home/narek/git/Shell/git.sh'
alias wifi='/home/narek/git/Shell/wifi.sh'

alias sag='sudo apt-get'
alias sagp='sa purge -y'
alias sagu='sa update -y'
alias sagi='sa install -y'
alias sagug='sa upgrade -y'
alias sagac='sa autoclean -y'
alias sagif='sa install -f -y'
alias sagar='sa autoremove -y'

alias gs='gg -s'
alias gp='gg -p'
alias gu='gg -u'
alias gk='gg -k'
alias gl='git log'
alias gc='git clone'
