#!/bin/bash

alias la='ls -A'
alias ll='ls -l'
alias lR='ls -R'
alias l1='ls -1'
alias lss='ls *'
alias laa='la *'
alias lls='ll *'
alias la1='la -1'
alias lR1='lR -1'
alias lla='ll -A'
alias laR='la -R'

alias su='sudo su'
alias py='python3'
alias py2='python2'
alias rmf='rm -rf'
alias open='gnome-open'
alias rmysql='mysql -u root -p'
alias chrome='chromium-browser'
alias jupyter='jupyter-notebook'

alias gg='/home/narek/git/Shell/git.sh'
alias wifi='/home/narek/git/Shell/wifi.sh'

alias sag='sudo apt-get'
alias sagp='sag purge -y'
alias sagu='sag update -y'
alias sagi='sag install -y'
alias sagug='sag upgrade -y'
alias sagac='sag autoclean -y'
alias sagif='sag install -f -y'
alias sagar='sag autoremove -y'

alias gs='gg -s'
alias gp='gg -p'
alias gu='gg -u'
alias gk='gg -k'
alias gl='git log'
alias gc='git clone'
