#!/bin/bash

alias la='ls -A'
alias ll='ls -l'
alias lr='ls -R'

alias rmf='rm -rf'
alias cls='clear && ls'
alias tmex='tmux; exit'

alias rebash='~/.bashrc'

alias gad='git add'
alias glg='git log'
alias gdf='git diff'
alias gpl='git pull'
alias gps='git push'
alias gcl='git clone'
alias gsh='git stash'
alias gbr='git branch'
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit -m'

alias py='python3'
alias python='python3'
alias pep='pycodestyle'
alias jupyter='jupyter-notebook'
alias django-run='python3 manage.py runserver'
alias django-migrate='python3 manage.py makemigrations && python3 manage.py migrate'
