#!/bin/bash

# General
alias la='ls -A'
alias ll='ls -l'
alias lr='ls -R'

alias rmf='rm -rf'
alias cls='clear && ls'
alias tmex='tmux; exit'

alias rebash='~/.bashrc'

# Git
alias gad='git add'
alias glg='git log'
alias gdf='git diff'
alias gpl='git pull'
alias gps='git push'
alias gcl='git clone'
alias gsh='git stash'
alias gbr='git branch'
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit -m'

# Python
alias py='python3'
alias python='python3'
alias pip='pip3'
alias pep='pycodestyle'
alias django-run='python3 manage.py runserver'
alias django-migrate='python3 manage.py makemigrations && python3 manage.py migrate'
alias clean-pycache='find . -type d -name "__pycache__" -exec rm -r {} +'
alias pylinter='sh ~/Code/Shell/full-python-linter.sh'

# G++ compiler
alias g11='g++ -std=c++11'
alias g17='g++ -std=c++17'

# Docker
alias dc-up='docker compose up'
alias dc-build='docker compose build'
